Domi
Domino-Blockchain/DApps pull request #1
Opened 2023-04-07 06:54 UTC by rs-Nenad

2023-04-11 13:55 UTC, sviatoslav-alekseev requested changes

2023-04-11 13:55 UTC, sviatoslav-alekseev commented on solana-hello-world/app/pages/index.tsx
> +
```suggestion
```

2023-04-24 13:11 UTC, dragvs requested changes

2023-04-24 13:11 UTC, dragvs commented on domichain-hello-world/app/pages/index.tsx
> +        <button onClick={print}>CLICK</button>
This one looks strange, do we still need it? I guess we can just print wallet address in the console or a hidden block

2023-04-24 13:55 UTC, sviatoslav-alekseev requested changes

2023-04-27 13:50 UTC, dragvs approved these changes

2023-04-27 13:50 UTC, merged